# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build the docker image and scan with ShiftLeft
      - name: Build the Docker image and scan with ShiftLeft
        env: 
           CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
           CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
           CHKP_CLOUDGUARD_ENV: ${{ secrets.CHKP_CLOUDGUARD_ENV }}
           SHIFTLEFT_REGION: eu1
        run: |
           docker build -t shiftleftexample/gdc-python .
           docker save -o shiftleftexample.tar shiftleftexample/gdc-python
           docker run --rm -e SHIFTLEFT_REGION -e CHKP_CLOUDGUARD_ID -e CHKP_CLOUDGUARD_SECRET -v $PWD:$PWD -w $PWD checkpoint/shiftleft shiftleft image-scan -i shiftleftexample.tar -r -2002 -e $CHKP_CLOUDGUARD_ENV
  codescan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Scan source code with ShiftLeft Container and provide result
        env: 
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
          CHKP_CLOUDGUARD_ENV: ${{ secrets.CHKP_CLOUDGUARD_ENV }}
          SHIFTLEFT_REGION: eu1
        run: docker run --rm -e SHIFTLEFT_REGION -e CHKP_CLOUDGUARD_ID -e CHKP_CLOUDGUARD_SECRET -v $PWD:$PWD -w $PWD checkpoint/shiftleft shiftleft code-scan -s . -r -2003 -e $CHKP_CLOUDGUARD_ENV

  onemore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository 
      - uses: actions/checkout@v2
        with:
          repository: DDuarte/springshell-rce-poc
      # Build the docker image and scan with ShiftLeft
      - name: Build the Docker image and scan with ShiftLeft
        env: 
           CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
           CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
           CHKP_CLOUDGUARD_ENV: ${{ secrets.CHKP_CLOUDGUARD_ENV }}
           SHIFTLEFT_REGION: eu1
        run: |
           docker build -t rce .
           docker save -o rce.tar rce
           docker run --rm -e SHIFTLEFT_REGION -e CHKP_CLOUDGUARD_ID -e CHKP_CLOUDGUARD_SECRET -v $PWD:$PWD -w $PWD checkpoint/shiftleft shiftleft image-scan -i rce.tar -r -2002 -e $CHKP_CLOUDGUARD_ENV
